name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download-sources-from-crowdin:
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: grafana-pr-automation
      - name: "Get vault secrets"
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@2c6a031846caccb893594248836c4f42bf73a125 # main
        with:
          # Vault secret paths:
          # - ci/repo/grafana/grafana-mssql-datasource/grafana-frontend-crowdin-token
          repo_secrets: |
            CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Download from Crowdin
        uses: grafana/grafana-github-actions/crowdin-download@36cd995b957c918d9f7c83953149d2507a53c2fd # main
        with:
          crowdin_token: ${{ fromJSON(steps.vault-secrets.outputs.secrets).CROWDIN_TOKEN }}
          crowdin_project_id: 56
          pr_labels: "area/i18n, no-changelog"
          github_board_id: 1085 # Grafana Data Sources project
          github_repo_token: ${{ steps.get-github-app-token.outputs.token }}
