name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  download-sources-from-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-download.yml@main
    with:
      crowdin_project_id: 56
      pr_labels: 'area/i18n,no-changelog'
